### ISSUE TITLE
是否引入 babel-plugin-transform-decorators-legacy

### ISSUE THREAD

**Issue by eternalsky** [uxcore/uxcore-tools#14]
decorator 的老提案被从 babel 官方包里踢掉，换做使用 babel-plugin-transform-decorators-legacy 来支持。需要调研新旧提案具体的区别，来判断是否可以引入 legacy 方案来支持老提案的装饰器。

* 判断的标准是老方案在新方案使用后是否是可以平滑地过渡的。

**Comment by tommytroylin** [comment]
现在 typescript 和 decorators-legacy 的 decorator 都是老的提案。
nowa1 中已经加入 transform-decorators-legacy 并且稳定运行了很久了~
老提案编译实现都没有改动,只是npm包和配置重命名为了与新提案区分开。
新提案转义babel还在开发中。一时半会儿还用不上。

**Comment by eternalsky** [comment]
@tommytroylin 但组件层一直还没有引入这一插件，所以要看一下新老方案的差距，如果是一个注定马上要去除的标准，且不能和新标准兼容，那还不如先不引入。如果可以兼容，可以考虑引入。
